[tox]
isolated_build = true
env_list =
    ; flake8
    ; black
    py39
    py310
    py311
    py312
    py313
    py314.0a1
    tests

[testenv]
deps =
    -rrequirements-dev.txt

[testenv:flake8]
allowlist_externals = flake8
commands = flake8 .

[testenv:black]
commands = black .

[testenv:tests]
commands = 
    python -m pytest
